language: go

go:
  # - 1.7.x
  # - 1.8.x
  # - 1.9.x
  # - 1.10.x
  # - 1.11.x
  # - 1.12.x
  # - 1.13.x
  # - 1.16.x
  # - 1.17.x
  # - 1.18.x
  # - 1.19.x
  - 1.20.x
  # - tip

install:
  - export PATH=$PATH:$HOME/gopath/bin
  # - go get -u github.com/go-ego/cedar
  - go get -t -d -v ./...
  # - go get -u -v -t ./...
# notifications:
#   email:
#     - .com
